import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";
import { UploadButton } from "~/utils/uploadthing";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const { mutate } = api.post.deleteImage.useMutation();

  return (
    <>
      <Head>
        <title>Dish rental</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center gap-4">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Dish rental
          </h1>
          <h2 className="text-2xl text-white">
            Rent your dishes and make money
          </h2>
          <Image
            src="/images/dish_rent.png"
            alt="dish-rental"
            width={500}
            height={500}
          />
        </div>

        <div className="flex flex-col items-center gap-2">
          <p className="text-3xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <AuthShowcase />
        </div>
        <UploadButton
          endpoint="imageUpload"
          onClientUploadComplete={(res) => {
            // Do something with the response
            console.log("Files: ", res);
            // TODO: save url to db with id of the user
            alert("Upload Completed");
          }}
          onUploadError={(error: Error) => {
            // Do something with the error.
            alert(`ERROR! ${error.message}`);
          }}
        />
        <button
          onClick={() =>
            // deleteFiles("4867186a-23e9-45e1-bbde-517f1865ed95-hk0kl7.png")
            // mutate("4867186a-23e9-45e1-bbde-517f1865ed95-hk0kl7.png")
            // deleteValue()
            mutate("2f766643-edc8-41f5-9c20-e8bb2ab7ca70-1vuq0w.png")
          }
        >
          Delete image
        </button>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
